config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  get 'users/index'

  get 'users/new'

  get  '/signup',  to: 'users#new'

  post '/signup',  to: 'users#create'

  get 'home/index'

  resources :microposts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { email.downcase! }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 }, 
  				format: { with: VALID_EMAIL_REGEX }, 
  				uniqueness: { case_sensitive: false }
  	has_secure_password
  	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = t('INVALID_LOGIN')
      render 'new'
    end
  end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% provide :title, t('HOME') %>

<div class="container">
	<div id="promo">
		<div class="row">
			<div class="col-md-7">
				<ul class="bxslider">
				  <li><%=image_tag("promo1.jpg", alt: "Promo 1") %></li>
				  <li><%=image_tag("promo2.jpg", alt: "Promo 2") %></li>
				  <li><%=image_tag("promo3.jpg", alt: "Promo 3") %></li>
				</ul>
			</div>
			<div class="col-md-5">
				<center><h2><%= t('WELCOME_TO_SAMPLE_APP') %></h2>
					<p><%= t('HOME_PAGE_FOR_SAMPLE_APP') %></p>
					<br>
					<p><%= link_to image_tag("rails.png", alt: "Rails logo", height: "100", width: "auto"),
	            "http://rubyonrails.org/" %></p>
	        <br>
	        <p><%= link_to t('SIGNUP_NOW'), new_user_path, class: "btn btn-lg btn-default" %></p>
	      </center>
			</div>
		</div>
	</div>
</div>

<div id="bottom-promo" class="parallax">
	<div class="apex-dn"></div>
	<ul class="bxslider">
		<li><p>Rails is the most well thought-out web development framework I’ve ever used. And that’s in a decade of doing web applications for a living. I’ve built my own frameworks, helped develop the Servlet API, and have created more than a few web servers from scratch. Nobody has done it like this before.</p>
			<span class="author pull-right clear">James Duncan Davidson</span>
		</li>
		<li><p>Ruby on Rails is a breakthrough in lowering the barriers of entry to programming. Powerful web applications that formerly might have taken weeks or months to develop can be produced in a matter of days.</p>
			<span class="author pull-right clear">Tim O’Reilly</span></li>
		<li><p>Ruby on Rails…is both revolutionary as a language as well as a framework.</p>
			<span class="author pull-right clear">Klaus-Michael Vogelberg</span>
		</li>
	</ul>
</div>
<%= yield %>

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">Rails Test App</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('HOME'), root_path %></li>
        <li><%= link_to t('HELP'), '#' %></li>
        <% if logged_in? %>
        <li><%= link_to t('USERS'), '#' %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t('ACCOUNT') %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t('PROFILE'), current_user %></li>
            <li><%= link_to t('SETTINGS'), '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to t('LOGOUT'), logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to t('LOGIN'), login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> | Ruby on Rails Tutorial Sample App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
  <script type="text/javascript">
  $(document).ready(function(){
    $('#promo .bxslider').bxSlider({
      auto:  true,
      adaptiveHeight: false
    });
    $('#bottom-promo .bxslider').bxSlider({
      auto:  true,
      controls: false,
      pager: false,
      pause: 6000,
      adaptiveHeight: true
    });
  });
  </script>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide :title, t('USERS') %>

app/views/users/new.html.erb
<div class="container">
	<center><h1><%= t('Signup') %></h1></center>
	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
	    <%= form_for(@user, url: signup_path) do |f| %>
	    <%= render 'shared/error_messages' %>
	    <div class="form-group">
	      <%= f.label :name %>
	      <%= f.text_field :name, class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.label :email %>
	      <%= f.email_field :email, class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.label :password %>
	      <%= f.password_field :password, class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.label :password_confirmation, t('Confirmation') %>
	      <%= f.password_field :password_confirmation, class: "form-control" %>
	    </div>
	      <%= f.submit t('CREATE_MY_ACCOUNT'), class: "btn btn-lg btn-primary full-width" %>
	    <% end %>
	  </div>
	</div>
</div>

app/views/users/show.html.erb
<% provide :title, t('USERS') %>
<p>Find me in app/views/users/index.html.erb</p>